### PR TITLE
Translate error message (About #8)

### PR DESCRIPTION
**Pull request by anolek**
Hi,

This PR is about this issue #8. I think it's all good, but If i miss something, tell me :)

Thanks !

### CODE REVIEW

**Comment by dead-horse** [comment]
https://github.com/koajs/parameter/blob/master/.travis.yml please change the version here to 4 & 6

**Comment by anolek** [comment]
@dead-horse done

**Comment by dead-horse** [comment]
👍

**Comment by dead-horse** [comment]
2.1.0

**Comment by fengmk2** [comment]
👍

**Pull request merged**
